name: Services
on: push

jobs:
  test-services:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: installation redis-cli
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools
      - run: |
          echo 'test connexion' $(redis-cli -h localhost PING)
          redis-cli -h localhost SET user:1 '{"id":1,"name":"Henri"}'
          redis-cli -h localhost SET user:2 '{"id":2,"name":"Alice"}'
          echo "user 1: $(redis-cli -h localhost GET user:1)"
          echo "user 2: $(redis-cli -h localhost GET user:2)"
