name: staging workflow
on:
  push:
    branches: staging
  pull_request:
    branches: staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://mon-application-staging.fr
    steps:
      - run: |
          echo Deploy to staging
