name: Container Docker

on: push

jobs:
  classique:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Job classique"
          echo "node -v: $(node -v)"
  avec-container:
    runs-on: ubuntu-latest
    container:
      # image: node:22
      image: henriteinturier/demonstration-image-prive
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      env:
        NODE_ENV: "production"
      volumes:
        - my_volume:/app/temp
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Job avec container"
          echo "node -v: $(node -v)"
          echo "NODE_ENV: $NODE_ENV"
      - run: |
          echo "Hello from Volume" > /app/temp/hello.txt

      - run: |
          cat /app/temp/hello.txt
