name: matrix

on:
  push:
    branches:
      - main

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]

    steps:
      - run: echo "Running on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"
