name: Permissions

on:
  push:
    branches:
      - main

jobs:
  permissions-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello, world!"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "secrets github: ${{ secrets.GITHUB_TOKEN }}"
