name: production workflow
on:
  push:
    branches: staging

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://mon-application.staging.fr
    steps:
      - run: |
          echo Deploy to production

# lien vers environnement
# https://github.com/<user_Name>/>repo_name>/deployments/<environment_name>
