name: staging workflow
on:
  push:
    branches: staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://mon-application.staging.fr
    steps:
      - run: |
          echo Deploy to production
          echo "DATABASE_URL" ${{ vars.DATABASE_URL }}
          echo "secret password" ${{ secrets.DATABASE_PASSWORD }}

# lien vers environnement
# https://github.com/<user_Name>/>repo_name>/deployments/<environment_name>
